# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42eb1e0d9cd6b7a554f4ebcb61521e92a37d6d3ab7517f463ccd7afa7ff201ff955ab4398b157db5d4caff0e252256999d32d98b669e3a6ca89ec01e92105577

test:
  secret_key_base: c07a87d0792807547555c3736d2feb9cc70aa3309d2957b5891baf27a02e380ec1be1e8d732441cf84cdafbff8d6af015278cb75c9bfb3de87bd1aad6534c4f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
